---
title: "group_comparision_adult_child"
author: "Yiming"
date: "11/12/2018"
output: pdf_document
---


```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lme4)
library(psyphy)
library(sjPlot)
library(dplyr)
library(ggplot2)
library(lmSupport)
# if (!("pacman" %in% installed.packages()[,])) {
#     install.packages("pacman")
#   }
# library(pacman)
# pacman::p_load(dplyr, ggplot2, knitr, psyphy, lme4, sjPlot)
```

```{r ggplot-themes}
theme.custom <- theme(plot.title = element_text(size=16, face="bold"),
                      axis.title.x = element_text(size=14),
                      axis.title.y = element_text(size=14),
                      strip.text = element_text(size=14),
                      axis.text = element_text(size=11),
                      legend.position="bottom", 
                      legend.title=element_blank(),
                      legend.text=element_text(size=11))
```

# create the combined files
```{r load-files}
df_child <- read.csv(file = "~/moco-psychophysics-child-adult/analysis/data/moco-child.csv", header = TRUE,sep=",")
df_adult <- read.csv(file = "~/moco-psychophysics-child-adult/analysis/data/moco-adult.csv", header = TRUE)
df_adult$Speed <- factor(df_adult$Speed, labels = c("2deg/s", "8deg/s"))
df_child$Speed <- factor(df_child$Speed, labels = c("2deg/s", "8deg/s"))
df_child2 <- df_child %>%
   dplyr::select(SubID, PatternType, RT, Acc, Speed, Gender, Coh)
df_adult2 <- df_adult %>%
   dplyr::select(SubID, PatternType, RT, Acc, Speed, Gender, Coh)
df<-bind_rows(df_child2, df_adult2) 
df<- df %>%
  mutate(group=c(rep('child',nrow(df_child2)),rep('adult',nrow(df_adult2))))
write.csv(df, file = "CombinedData.csv")
```

```{r load-data}
df <- read.csv(file="CombinedData.csv", header=TRUE, sep=",")

df %>% 
  group_by(Gender, group, SubID, PatternType, Speed, Coh) %>% 
  summarize(N.corr = sum(Acc), 
            N.tot = n(), 
            Pct.Corr = N.corr/N.tot,
            RT.mean=mean(RT, na.rm = T),
            RT.sd=sd(RT, na.rm = T)) -> 
  df3
```

# Accuracy group comparison
```{r acc-logit-initial, eval=FALSE}
form.acc.logit1<- Acc ~ Gender + Coh + Speed + PatternType + group + Coh*PatternType*Speed + (1|SubID) 
model.acc.logit1 <- glmer(formula = form.acc.logit1, family=binomial(mafc.logit(2)), data = df)
summary(model.acc.logit1)
```
```{r acc-logit-full, eval=FALSE}
form.acc.logit2<- Acc ~ Gender + Coh + Speed + group + Coh*PatternType+ Coh*Speed+group*Coh+group*PatternType+group*Speed+ (1|SubID) 
model.acc.logit2 <- glmer(formula = form.acc.logit2, family=binomial(mafc.logit(2)), data = df)
summary(model.acc.logit2)
car::Anova(model.acc.logit2)
```

# effect size
``` {r acc-effect-size}
# This is not the effect size in GLM model
effsize::cohen.d(Pct.Corr~group,data=df3,paired=F)  # df3 and df4 makes a large difference, which shall I choose?
effsize::cohen.d(Pct.Corr~Gender,data=df4,paired=F)


# calculate effect size in GLM
library('pwr')
compute.es::chies(50.40, 59)
modelEffectSizes(model.acc.logit2 ) 

modelSummary(model.acc.logit2)
form.rt <- log(RT)~ Coh + Speed + PatternType + group + Coh*PatternType+group*Speed + (1|SubID)
model.rt <- lmer(formula = form.rt, data = df)
modelSummary(model.fixed.rt2)
```

``` {r mean-sd}
df %>% 
  group_by(Gender, group, SubID) %>% 
  summarize(N.corr = sum(Acc), 
            N.tot = n(), 
            Pct.Corr = N.corr/N.tot,
            RT.mean=mean(RT, na.rm = T),
            RT.sd=sd(RT, na.rm = T)) -> 
  df4
df.bysub.bycond <- df4 %>%
  group_by(group) %>%
  summarise(pcorr.mean=mean(Pct.Corr),
         pcorr.sd=sd(Pct.Corr),
         RT.mean.mean=mean(RT.mean),
         RT.mean.sd=sd(RT.mean) )

df.bysub.bycond <- df4 %>%
  group_by(Gender) %>%
  summarise(pcorr.mean=mean(Pct.Corr),
         pcorr.sd=sd(Pct.Corr),
         RT.mean.mean=mean(RT.mean),
         RT.mean.sd=sd(RT.mean) )
df.bysub.bycond

df.bysub.bycond <- df3 %>%
  group_by(Speed) %>%
  summarise(pcorr.mean=mean(Pct.Corr),
         pcorr.sd=sd(Pct.Corr),
         RT.mean.mean=mean(RT.mean),
         RT.mean.sd=sd(RT.mean) )
df.bysub.bycond

df.bysub.bycond <- df3 %>%
  group_by(PatternType) %>%
  summarise(pcorr.mean=mean(Pct.Corr),
         pcorr.sd=sd(Pct.Corr),
         RT.mean.mean=mean(RT.mean),
         RT.mean.sd=sd(RT.mean) )
df.bysub.bycond

df.bysub.bycond <- df3 %>%
  group_by(Coh) %>%
  summarise(pcorr.mean=mean(Pct.Corr),
         pcorr.sd=sd(Pct.Corr),
         RT.mean.mean=mean(RT.mean),
         RT.mean.sd=sd(RT.mean) )
df.bysub.bycond
```

#### Rt group comparison
```{r rt-initial, eval=FALSE}
form.fixed.rt <- RT~ Coh + Speed + PatternType + (1|SubID)
model.fixed.rt <- lmer(formula = form.fixed.rt, data = df, REML=FALSE)
summary(model.fixed.rt)
```
```{r rt-log-initial, eval=FALSE}
form.fixed.rt1 <- log(RT)~ Coh + Speed + PatternType + (1|SubID)
model.fixed.rt1 <- lmer(formula = form.fixed.rt1, data = df, REML=FALSE)
summary(model.fixed.rt1)
```
```{r rt-log-full, eval=FALSE}
form.fixed.rt2 <- log(RT)~ Gender+ Coh + Speed + PatternType + Coh*PatternType*Speed + Coh*Speed+group*Coh+group*PatternType+group*Speed + (1|SubID)
model.fixed.rt2 <- lmer(formula = form.fixed.rt2, data = df, REML=FALSE)

summary(model.fixed.rt2)
car::Anova(model.fixed.rt2)
```

### Plot of actual  *p*(corr) and predicted *p*(corr) by condition
```{r p-corr-pattern-speed-plot-final, include=TRUE}
df_child3 <- df_child %>%
  filter(Group=="linear-radial coh [.15 .3 .45 .6]") %>%
   dplyr::select(SubID, PatternType, RT, Acc, Speed, Gender, Coh)
df_adult2 <- df_adult %>%
   dplyr::select(SubID, PatternType, RT, Acc, Speed, Gender, Coh)
df2<-bind_rows(df_child3, df_adult2) 
df2<- df2 %>%
  mutate(group=c(rep('child',nrow(df_child3)),rep('adult',nrow(df_adult2))))

df2 %>% 
  group_by(SubID, group, PatternType, Coh, Speed) %>% 
  summarize(N.corr = sum(Acc), 
            N.tot = n(), 
            Pct.Corr = N.corr/N.tot,
            RT.mean=mean(RT, na.rm = T),
            RT.sd=sd(RT, na.rm = T)) -> 
  df.summary
df.summary %>% 
  group_by( group,Coh,Speed,PatternType) %>% 
  summarize(pcorr.mean=mean(Pct.Corr),
         pcorr.sd=sd(Pct.Corr),
         RT.mean.mean=mean(RT.mean),
         RT.mean.sd=sd(RT.mean)) -> 
  df.bygroup.bycond
# add fitted line
xseq<-seq(0.05,0.6,len=100)
df.summary$id<-with(df.summary,interaction(Speed, PatternType, group, SubID))
nd<-data.frame(rep(xseq,8*54),id=rep(levels(df.summary$id),each=100))
# levels(nd$id)<-levels(df.bysub.byage.bycond$id)
mm <-matrix(unlist(strsplit(as.character(nd$id),"[.]")), ncol=4,byrow=TRUE)
nd$Speed<-gsub("[[:space:]]", "",factor(mm[,1]))
nd$PatternType<-factor(mm[,2])
nd$group<-factor(mm[,3])
nd$SubID<-factor(mm[,4])
colnames(nd)[1] <- "Coh"

model.acc.logit.dropgender <- update(model.acc.logit2, . ~ . - Gender)
nd$acc.pred<-predict(model.acc.logit.dropgender,newdata=nd,type="response",se.fit=TRUE) # obtain predicted values
model.fixed.rt.dropgender <- update(model.fixed.rt2, . ~ . - Gender)
nd$rt.pred<-exp(predict(model.fixed.rt.dropgender,newdata=nd, type="response", se.fit=TRUE)) # obtain predicted values

nd2 <- nd %>%
  group_by(group, Speed,Coh, PatternType) %>%
  summarize(acc.pred.mean=mean(acc.pred),
         acc.pred.se=sd(acc.pred)/sqrt(length(acc.pred)),
         RT.pred.mean=mean(rt.pred),
         RT.pred.se=sd(rt.pred)/sqrt(length(rt.pred)))
# df.bygender.bycond$Speed<-factor(df.bygender.bycond$Speed)
```
```{r plot-acc}
# Plot of ectual and predicted ACC
title_text <- 'Percentage of correct responses by Coherence, Pattern, and Speed'
pic.acc<-ggplot(data=df.bygroup.bycond, aes(x=Coh, y=pcorr.mean, color=group)) +
  geom_point(aes(group=group, color=group),size=2) +
  geom_line(data=nd2, aes(x=Coh,y=acc.pred.mean, group=group, color=group),size=1) +
  facet_grid(facets = Speed ~ PatternType) +
  labs(x="Coherence (%)", y="Percentage of Accuracy") +
  ggtitle(title_text) +
  scale_colour_hue(name="participant gender",    #Legend label, use darker colors
                      breaks=c("Female", "Male"),
                      labels=c("Female", "Male"))+
  theme_bw() +
  theme.custom +
  xlim(0.05, 0.6) +
  geom_hline(yintercept=0.5, linetype="dashed")

pic.acc
```

```{r plot-rt}
# Plot of extual and predicted ACC
title_text <- 'Reaction Times by Coherence, Pattern, and Speed'
pic.rt<-ggplot(data=df.bygroup.bycond, aes(x=Coh, y=RT.mean.mean, color=group)) +
  geom_point(aes(group=group, color=group),size=2) +
  geom_line(data=nd2, aes(x=Coh,y=RT.pred.mean, group=group, color=group),size=1) +
  facet_grid(facets = Speed ~ PatternType) +
  labs(x="Coherence (%)", y="Reaction times (s)") +
  ggtitle(title_text) +
  scale_colour_hue(name="group",    #Legend label, use darker colors
                      breaks=c("child", "adult"),
                     labels=c("Child", "Adult"))+
  theme_bw() +
  theme.custom +
  xlim(0.05, 0.6) 

pic.rt
```

```{r 15%-coherence-comparsion}
df_child3 <- df_child %>%
   dplyr::select(SubID, PatternType, RT, Acc, Speed, Gender, Coh)%>%
   dplyr::filter(Coh==0.15)
df_adult3 <- df_adult %>%
   dplyr::select(SubID, PatternType, RT, Acc, Speed, Gender, Coh)%>%
   dplyr::filter(Coh==0.15)
df1<-bind_rows(df_child3, df_adult3) 
df1<- df1 %>%
  mutate(group=c(rep('child',nrow(df_child3)),rep('adult',nrow(df_adult3))))
```
``` {r rt}
form.coh.rt <- RT~ group + Gender+ Speed + PatternType + (1|SubID)
model.coh.rt <- lmer(formula = form.coh.rt, data = df1, REML=FALSE)
summary(model.coh.rt)
car::Anova(model.coh.rt)
form.coh.rt1 <- RT~ group + Speed + PatternType + group*Speed + group*PatternType + Speed * PatternType + (1|SubID)
model.coh.rt1 <- lmer(formula = form.coh.rt1, data = df1, REML=FALSE)
summary(model.coh.rt1)
car::Anova(model.coh.rt1)
```

``` {r acc}
form.coh.acc1 <- Acc~ group + Speed + Gender + PatternType + group*Speed + group*PatternType + Speed * PatternType + (1|SubID)
model.coh.acc1 <- lmer(formula = form.coh.acc1, data = df1, REML=FALSE)
summary(model.coh.acc1)
car::Anova(model.coh.acc1)
```


``` {r SDT}
library(psycho)
# Let's simulate three participants with different results at a perceptual detection task
df_child4 <- df_child %>%
   dplyr::select(SubID, PatternType, RT, Acc, Speed, Gender, Coh, Response)%>%
   dplyr::filter(Coh==0.15)
df_adult4 <- df_adult %>%
   dplyr::select(SubID, PatternType, RT, Acc, Speed, Gender, Coh, Response)%>%
   dplyr::filter(Coh==0.15)
df2<-bind_rows(df_child4, df_adult4) 
df.sdt<- df2 %>%
  mutate(group=c(rep('child',nrow(df_child4)),rep('adult',nrow(df_adult4)))) %>%
  group_by(SubID, group, Coh, PatternType, Speed, Gender) %>%
  summarize(n_hit = sum(Response=="L" & Acc=="TRUE", na.rm=T),
            n_fa  = sum(Response=="L" & Acc=="FALSE", na.rm=T),
            n_miss = sum(Response=="R" & Acc=="FALSE", na.rm=T),
            n_cr = sum(Response=="R" & Acc=="TRUE", na.rm=T))

indices <- neuropsychology::dprime(df.sdt$n_hit, df.sdt$n_fa, df.sdt$n_miss, df.sdt$n_cr)
df.new <- cbind(df.sdt, indices)
```

``` {r anova-SDT}
aov <- with(df.new, aov(dprime ~ Speed * PatternType * group * Gender +
                       Error(SubID / (Speed * PatternType)))
)
summary(aov)
aov <- with(df.new, aov(dprime ~ Speed + PatternType + group + Gender +
                       Error(SubID / (Speed + PatternType)))
)
summary(aov)
# sum sq = 138.83
aov_c <- with(df.new, aov(c ~ Speed + PatternType + group + Gender +
                       Error(SubID / (Speed + PatternType)))
)
summary(aov_c)
# sum sq 6.396
```

``` {r anova-plot}
myData <- aggregate(df.new$dprime,
    by = list(PatternType = df.new$PatternType, Gender = df.new$Gender),
    FUN = function(x) c(mean = mean(x), sd = sd(x),
                        n = length(x)))
myData <- do.call(data.frame, myData)
myData$se <- myData$x.sd / sqrt(myData$x.n)
ggplot(myData, aes(x=PatternType, y=x.mean, group=Gender, fill=Gender)) + 
  geom_bar(stat="identity",  
           position=position_dodge()) +
  geom_errorbar(aes(ymin=x.mean-se, ymax=x.mean+se), width=.2,position=position_dodge(.9))  + 
  labs( y = "Sensitivity (d')")+
   theme_classic()

myData <- aggregate(df.new$dprime,
    by = list(PatternType = df.new$PatternType, Speed = df.new$Speed),
    FUN = function(x) c(mean = mean(x), sd = sd(x),
                        n = length(x)))
myData <- do.call(data.frame, myData)
myData$se <- myData$x.sd / sqrt(myData$x.n)
myData$Speed<-factor(myData$Speed, levels=c("2","8"),labels= c("2 deg/sec","8 deg/sec"))
ggplot(myData, aes(x=PatternType, y=x.mean, group=Speed, fill=Speed)) + 
  geom_bar(stat="identity",  
           position=position_dodge()) +
  geom_errorbar(aes(ymin=x.mean-se, ymax=x.mean+se), width=.2,position=position_dodge(.9))  + 
  labs( y = "Sensitivity (d')")+
   theme_classic()

myData <- aggregate(df.new$c,
    by = list(Speed = df.new$Speed, Gender = df.new$Gender),
    FUN = function(x) c(mean = mean(x), sd = sd(x),
                        n = length(x)))
myData <- do.call(data.frame, myData)
myData$se <- myData$x.sd / sqrt(myData$x.n)
myData$Speed<-factor(myData$Speed, levels=c("2","8"),labels= c("2 deg/sec","8 deg/sec"))
ggplot(myData, aes(x=Speed, y=x.mean, group=Gender, fill=Gender)) + 
  geom_bar(stat="identity",  
           position=position_dodge()) +
  geom_errorbar(aes(ymin=x.mean-se, ymax=x.mean+se), width=.2,position=position_dodge(.9))  + 
  labs( y = "Response bias (c)", x = "Speed")+
   theme_classic()
```